import { Pipe, PipeTransform, inject } from '@angular/core'
import { TranslocoService } from '@jsverse/transloco'

type ActionMap = Record<string, string>
type LangActionMap = Record<string, ActionMap>

const LABELS: LangActionMap = {
  fr: {
    'category.created':             'Catégorie créée',
    'category.updated':             'Catégorie modifiée',
    'category.deleted':             'Catégorie supprimée',
    'category.reordered':           'Catégories réordonnées',
    'menu_item.created':            'Plat ajouté',
    'menu_item.updated':            'Plat modifié',
    'menu_item.deleted':            'Plat supprimé',
    'menu_item.toggled':            'Disponibilité modifiée',
    'user.created':                 'Caissier ajouté',
    'user.updated':                 'Caissier modifié',
    'user.deleted':                 'Caissier supprimé',
    'user.email_verified_by_admin': 'Email vérifié par admin',
    'restaurant.updated':           'Restaurant modifié',
    'restaurant.logo_uploaded':     'Logo mis à jour',
    'restaurant.blocked':           'Restaurant bloqué',
    'restaurant.unblocked':         'Restaurant débloqué',
    'subscription.created':         'Abonnement initié',
    'subscription.canceled':        'Abonnement annulé',
    'subscription.granted':         'Plan attribué (gratuit)',
    'order.created':                'Commande passée',
    'order.created_by_admin':       'Commande créée (admin)',
    'order.status_updated':         'Statut commande modifié',
    'order.gift_revoked':           'QR cadeau révoqué',
    'reservation.created':          'Réservation créée',
    'reservation.created_by_admin': 'Réservation créée (admin)',
    'reservation.status_updated':   'Statut réservation modifié',
    'expense.created':              'Dépense ajoutée',
    'expense.updated':              'Dépense modifiée',
    'expense.deleted':              'Dépense supprimée',
    'income.created':               'Revenu ajouté',
    'income.updated':               'Revenu modifié',
    'income.deleted':               'Revenu supprimé',
    'marketing_voucher.created':    'Bon de réduction créé',
    'marketing_voucher.updated':    'Bon de réduction modifié',
    'marketing_voucher.deleted':    'Bon de réduction supprimé',
    'marketing_voucher.redeemed':   'Bon de réduction utilisé',
    'plan.created':                 'Plan créé',
    'plan.updated':                 'Plan modifié',
    'plan.deleted':                 'Plan supprimé',
  },
  en: {
    'category.created':             'Category created',
    'category.updated':             'Category updated',
    'category.deleted':             'Category deleted',
    'category.reordered':           'Categories reordered',
    'menu_item.created':            'Item added',
    'menu_item.updated':            'Item updated',
    'menu_item.deleted':            'Item deleted',
    'menu_item.toggled':            'Availability toggled',
    'user.created':                 'Cashier added',
    'user.updated':                 'Cashier updated',
    'user.deleted':                 'Cashier removed',
    'user.email_verified_by_admin': 'Email verified by admin',
    'restaurant.updated':           'Restaurant updated',
    'restaurant.logo_uploaded':     'Logo updated',
    'restaurant.blocked':           'Restaurant blocked',
    'restaurant.unblocked':         'Restaurant unblocked',
    'subscription.created':         'Subscription initiated',
    'subscription.canceled':        'Subscription canceled',
    'subscription.granted':         'Plan granted (free)',
    'order.created':                'Order placed',
    'order.created_by_admin':       'Order created (admin)',
    'order.status_updated':         'Order status updated',
    'order.gift_revoked':           'Gift QR revoked',
    'reservation.created':          'Reservation created',
    'reservation.created_by_admin': 'Reservation created (admin)',
    'reservation.status_updated':   'Reservation status updated',
    'expense.created':              'Expense added',
    'expense.updated':              'Expense updated',
    'expense.deleted':              'Expense deleted',
    'income.created':               'Income added',
    'income.updated':               'Income updated',
    'income.deleted':               'Income deleted',
    'marketing_voucher.created':    'Voucher created',
    'marketing_voucher.updated':    'Voucher updated',
    'marketing_voucher.deleted':    'Voucher deleted',
    'marketing_voucher.redeemed':   'Voucher redeemed',
    'plan.created':                 'Plan created',
    'plan.updated':                 'Plan updated',
    'plan.deleted':                 'Plan deleted',
  },
  de: {
    'category.created':             'Kategorie erstellt',
    'category.updated':             'Kategorie aktualisiert',
    'category.deleted':             'Kategorie gelöscht',
    'category.reordered':           'Kategorien umsortiert',
    'menu_item.created':            'Gericht hinzugefügt',
    'menu_item.updated':            'Gericht aktualisiert',
    'menu_item.deleted':            'Gericht gelöscht',
    'menu_item.toggled':            'Verfügbarkeit geändert',
    'user.created':                 'Kassierer hinzugefügt',
    'user.updated':                 'Kassierer aktualisiert',
    'user.deleted':                 'Kassierer entfernt',
    'user.email_verified_by_admin': 'E-Mail vom Admin verifiziert',
    'restaurant.updated':           'Restaurant aktualisiert',
    'restaurant.logo_uploaded':     'Logo aktualisiert',
    'restaurant.blocked':           'Restaurant gesperrt',
    'restaurant.unblocked':         'Restaurant entsperrt',
    'subscription.created':         'Abonnement gestartet',
    'subscription.canceled':        'Abonnement gekündigt',
    'subscription.granted':         'Plan zugewiesen (kostenlos)',
    'order.created':                'Bestellung aufgegeben',
    'order.created_by_admin':       'Bestellung erstellt (Admin)',
    'order.status_updated':         'Bestellstatus aktualisiert',
    'order.gift_revoked':           'Geschenk-QR widerrufen',
    'reservation.created':          'Reservierung erstellt',
    'reservation.created_by_admin': 'Reservierung (Admin)',
    'reservation.status_updated':   'Reservierungsstatus aktualisiert',
    'expense.created':              'Ausgabe hinzugefügt',
    'expense.updated':              'Ausgabe aktualisiert',
    'expense.deleted':              'Ausgabe gelöscht',
    'income.created':               'Einnahme hinzugefügt',
    'income.updated':               'Einnahme aktualisiert',
    'income.deleted':               'Einnahme gelöscht',
    'marketing_voucher.created':    'Gutschein erstellt',
    'marketing_voucher.updated':    'Gutschein aktualisiert',
    'marketing_voucher.deleted':    'Gutschein gelöscht',
    'marketing_voucher.redeemed':   'Gutschein eingelöst',
    'plan.created':                 'Plan erstellt',
    'plan.updated':                 'Plan aktualisiert',
    'plan.deleted':                 'Plan gelöscht',
  },
  zh: {
    'category.created':             '创建分类',
    'category.updated':             '更新分类',
    'category.deleted':             '删除分类',
    'category.reordered':           '分类重新排序',
    'menu_item.created':            '添加菜品',
    'menu_item.updated':            '更新菜品',
    'menu_item.deleted':            '删除菜品',
    'menu_item.toggled':            '可用性已更改',
    'user.created':                 '添加收银员',
    'user.updated':                 '更新收银员',
    'user.deleted':                 '删除收银员',
    'user.email_verified_by_admin': '管理员已验证邮箱',
    'restaurant.updated':           '餐厅已更新',
    'restaurant.logo_uploaded':     'Logo已更新',
    'restaurant.blocked':           '餐厅已封禁',
    'restaurant.unblocked':         '餐厅已解封',
    'subscription.created':         '订阅已创建',
    'subscription.canceled':        '订阅已取消',
    'subscription.granted':         '套餐已授予（免费）',
    'order.created':                '订单已下',
    'order.created_by_admin':       '订单已创建（管理员）',
    'order.status_updated':         '订单状态已更新',
    'order.gift_revoked':           '礼品二维码已撤销',
    'reservation.created':          '预订已创建',
    'reservation.created_by_admin': '预订（管理员）',
    'reservation.status_updated':   '预订状态已更新',
    'expense.created':              '支出已添加',
    'expense.updated':              '支出已更新',
    'expense.deleted':              '支出已删除',
    'income.created':               '收入已添加',
    'income.updated':               '收入已更新',
    'income.deleted':               '收入已删除',
    'marketing_voucher.created':    '优惠券已创建',
    'marketing_voucher.updated':    '优惠券已更新',
    'marketing_voucher.deleted':    '优惠券已删除',
    'marketing_voucher.redeemed':   '优惠券已使用',
    'plan.created':                 '套餐已创建',
    'plan.updated':                 '套餐已更新',
    'plan.deleted':                 '套餐已删除',
  },
}

@Pipe({ name: 'auditActionLabel', standalone: true, pure: false })
export class AuditActionLabelPipe implements PipeTransform {
  private transloco = inject(TranslocoService)

  transform(action: string): string {
    const lang = this.transloco.getActiveLang() ?? 'fr'
    const map: ActionMap = LABELS[lang] ?? LABELS['fr']
    return map[action] ?? action
  }
}
